apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret-creds
            key: access-key-id
            namespace: external-secrets-op
          secretAccessKeySecretRef:
            name: aws-secret-creds
            key: secret-access-key
            namespace: external-secrets-op
